package progra1final;

import javax.swing.JOptionPane;

public class realizarSorteo extends javax.swing.JFrame {

    /**
     * Creates new form realizarSorteo
     */
    public realizarSorteo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Realización del sorteo");

        jButton1.setText("Lotería");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lotto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Bingo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tiempos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // loteria
        sorteoLoteria loteria = new sorteoLoteria();
        int ganador = loteria.sacarGanadorLoteria();
        loteria.setGanadorLoteria(ganador);
        String fechaSorteoLoteria = loteria.fechaLoteria();
        loteria.setFechaLoteria(fechaSorteoLoteria);
        A_InicioPrograma.ganadoresLote.append(loteria);
        
        JOptionPane.showMessageDialog(this, "El numero ganador: " + ganador);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // lotto
        sorteoLotto lotto = new sorteoLotto();
        int numUno = lotto.sacarNumUno();
        lotto.setNumUno(numUno);
        int numDos = lotto.sacarNumDos();
        lotto.setNumDos(numDos);
        int numTres = lotto.sacarNumTres();
        lotto.setNumTres(numTres);
        int numCuatro = lotto.sacarNumCuatro();
        lotto.setNumCuatro(numCuatro);
        int numCinco = lotto.sacarNumCinco();
        lotto.setNumCinco(numCinco);
        int numSeis = lotto.sacarNumSeis();
        lotto.setNumSeis(numSeis);
        int numSiete = lotto.sacarNumSiete();
        lotto.setNumSiete(numSiete);
        String fechaSorteoLotto = lotto.fechaLotto();
        lotto.setFechaLotto(fechaSorteoLotto);
        A_InicioPrograma.ganadoresLotto.append(lotto);
        
        JOptionPane.showMessageDialog(this, "Los numeros ganadores son: " + numUno + ", " + numDos + ", " + numTres + ", " + numCuatro + ", " + numCinco + ", " + numSeis + ", " + numSiete);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // tiempos
        sorteoTiempos tiempos = new sorteoTiempos();
        int jugada = tiempos.sacarJugada();
        tiempos.setJugada(jugada);
        int principal = tiempos.sacarPrincipal();
        tiempos.setPrincipal(principal);
        String fechaSorteoTiempos = tiempos.fechaTiempos();
        tiempos.setFechaTiempos(fechaSorteoTiempos);
        A_InicioPrograma.ganadoresTiempos.append(tiempos);
        
        JOptionPane.showMessageDialog(this, "La jugada ganadora es: " + jugada);
        JOptionPane.showMessageDialog(this, "El número principal ganador es: " + principal);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // bingo
        sorteoBingo bingo = new sorteoBingo();
        int numbUno = bingo.sacarNumbUno();
        bingo.setNumbUno(numbUno);
        int numbDos = bingo.sacarNumbDos();
        bingo.setNumbDos(numbDos);
        int numbTres = bingo.sacarNumbTres();
        bingo.setNumbTres(numbTres);
        int numbCuatro = bingo.sacarNumbCuatro();
        bingo.setNumbCuatro(numbCuatro);
        int numbCinco = bingo.sacarNumbCinco();
        bingo.setNumbCinco(numbCinco);
        int numbSeis = bingo.sacarNumbSeis();
        bingo.setNumbSeis(numbSeis);
        int numbSiete = bingo.sacarNumbSiete();
        bingo.setNumbSiete(numbSiete);
        int numbOcho = bingo.sacarNumbOcho();
        bingo.setNumbOcho(numbOcho);
        int numbNueve = bingo.sacarNumbNueve();
        bingo.setNumbNueve(numbNueve);
        String fechaSorteoBingo = bingo.fechaBingo();
        bingo.setFechaBingo(fechaSorteoBingo);
        A_InicioPrograma.ganadoresBingo.append(bingo);
       
        JOptionPane.showMessageDialog(this, "Los numeros ganadores son: " + numbUno + ", " + numbDos + ", " + numbTres + ", " + numbCuatro + ", " + numbCinco + ", " + numbSeis + ", " + numbSiete + ", " + numbOcho + ", " + numbNueve);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(realizarSorteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(realizarSorteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(realizarSorteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(realizarSorteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new realizarSorteo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
